# Generated by Django 4.1.5 on 2023-02-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('mail', models.EmailField()),
                ('auto',  models.CharField(max_length=30)),
                ('oferta',  models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('mail', models.EmailField()),
                ('modelo', models.IntegerField()),
                ('kilometros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('fechaDeEntrega', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
        ),
    ]
